begin;
create extension if not exists pg_trgm;
create table public.profiles(id uuid primary key references auth.users on delete cascade,display_name text,role text not null default 'viewer' check(role in ('admin','manager','viewer')),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create function public.crm_role() returns text language sql stable security definer set search_path=public as $$ select role from profiles where id=auth.uid() $$;
create function public.new_profile() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into profiles(id,display_name) values(new.id,new.email);return new;end $$;
create trigger auth_profile after insert on auth.users for each row execute function public.new_profile();
create table public.projects(id text primary key,name text not null,region text,district text,address text,category text,type text,stage text,priority text,area_m2 numeric check(area_m2>=0),lat double precision check(lat between -90 and 90),lng double precision check(lng between -180 and 180),start_date text,deadline text,description text,verified_at date,owner_id uuid references profiles,legacy jsonb not null default '{}',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check((lat is null)=(lng is null)));
create table public.companies(id uuid primary key default gen_random_uuid(),name text not null,normalized_name text not null,legal_name text,inn text unique,oked text,registration_number text,legal_address text,actual_address text,website text,main_phone text,main_email text,country text,region text,notes text,source text,source_url text,verified_at date,registry_provider text,registry_response jsonb,legacy jsonb not null default '{}',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index companies_name_trgm on companies using gin(normalized_name gin_trgm_ops);
create table public.people(id uuid primary key default gen_random_uuid(),first_name text not null,last_name text,position text,company_id uuid references companies,phone text,additional_phone text,email text,telegram text,whatsapp text,notes text,source text,verified_at date,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.project_participants(id uuid primary key default gen_random_uuid(),project_id text not null references projects,company_id uuid not null references companies,role text not null,person_id uuid references people,comment text,source text,verified_at date,legacy jsonb not null default '{}',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(project_id,company_id,role));
create table public.project_sections(id uuid primary key default gen_random_uuid(),project_id text not null references projects,section text not null,status text not null default 'Уточняется',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(project_id,section));
create table public.project_participant_sections(id uuid primary key default gen_random_uuid(),participant_id uuid not null references project_participants on delete cascade,section text not null,status text not null default 'Уточняется',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(participant_id,section));
create table public.specifications(id uuid primary key default gen_random_uuid(),project_id text not null references projects,section text not null,source text,name text not null,storage_path text not null unique,mime_type text,file_size bigint,status text not null default 'uploaded' check(status in ('uploaded','processing','parsed','failed')),uploader uuid references profiles,error_code text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.specification_items(id uuid primary key default gen_random_uuid(),specification_id uuid not null references specifications on delete cascade,original_name text not null,normalized_name text,section text,category text,manufacturer text,model text,article text,dn numeric,pn numeric,kvs numeric,voltage text,power text,unit text,quantity numeric check(quantity>=0),technical_parameters jsonb,notes text,confidence numeric check(confidence between 0 and 1),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.products(id uuid primary key default gen_random_uuid(),manufacturer text,brand text,article text,name text not null,category text,description text,dn numeric,pn numeric,kvs numeric,technical_parameters jsonb,purchase_price numeric check(purchase_price>=0),currency text,sales_price numeric check(sales_price>=0),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.product_matches(id uuid primary key default gen_random_uuid(),specification_item_id uuid not null references specification_items on delete cascade,product_id uuid references products,confidence numeric check(confidence between 0 and 1),reason text,match_status text not null check(match_status in ('matched','suggested','manual_review','unmatched','rejected')),reviewed_by uuid references profiles,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.opportunities(id uuid primary key default gen_random_uuid(),project_id text not null references projects,section text not null,name text not null,value_type text not null check(value_type in ('confirmed','estimated','unknown')),currency text not null default 'UZS',amount numeric check(amount>=0),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check((value_type='unknown' and amount is null) or value_type<>'unknown'));
create table public.calculations(id uuid primary key default gen_random_uuid(),opportunity_id uuid not null references opportunities,project_id text not null references projects,currency text not null,parameters jsonb not null,created_by uuid references profiles,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.calculation_items(id uuid primary key default gen_random_uuid(),calculation_id uuid not null references calculations,specification_item_id uuid references specification_items,quantity numeric,purchase_price numeric,currency text,sales_price numeric,delivery numeric,customs_duty numeric,certification numeric,vat numeric,markup numeric,margin numeric,additional_costs numeric,total numeric,parameters jsonb not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.activities(id uuid primary key default gen_random_uuid(),project_id text references projects,company_id uuid references companies,person_id uuid references people,type text not null,description text not null,date timestamptz not null default now(),user_id uuid references profiles default auth.uid(),next_action text,next_action_date date,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.sources(id uuid primary key default gen_random_uuid(),project_id text references projects,company_id uuid references companies,name text not null,url text,verified_at date,raw jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.history(id uuid primary key default gen_random_uuid(),entity text not null,entity_id text not null,project_id text,user_id uuid,operation text not null,old_value jsonb,new_value jsonb,created_at timestamptz not null default now());
create function public.audit_change() returns trigger language plpgsql security definer set search_path=public as $$
declare before_row jsonb;after_row jsonb;begin
 if TG_OP<>'INSERT' then before_row=to_jsonb(old);end if;
 if TG_OP<>'DELETE' then after_row=to_jsonb(new);end if;
 insert into history(entity,entity_id,project_id,user_id,operation,old_value,new_value) values(TG_TABLE_NAME,coalesce(after_row->>'id',before_row->>'id'),case when TG_TABLE_NAME='projects' then coalesce(after_row->>'id',before_row->>'id') else coalesce(after_row->>'project_id',before_row->>'project_id') end,auth.uid(),TG_OP,before_row,after_row);
 return coalesce(new,old);end $$;
create function public.touch_updated() returns trigger language plpgsql as $$ begin new.updated_at=now();return new;end $$;
alter table public.projects enable row level security;
create policy read_member on public.projects for select to authenticated using(public.crm_role() in ('admin','manager','viewer'));
create policy write_member on public.projects for all to authenticated using(public.crm_role() in ('admin','manager')) with check(public.crm_role() in ('admin','manager'));
create trigger audit after insert or update or delete on public.projects for each row execute function public.audit_change();
create trigger updated before update on public.projects for each row execute function public.touch_updated();
alter table public.companies enable row level security;
create policy read_member on public.companies for select to authenticated using(public.crm_role() in ('admin','manager','viewer'));
create policy write_member on public.companies for all to authenticated using(public.crm_role() in ('admin','manager')) with check(public.crm_role() in ('admin','manager'));
create trigger audit after insert or update or delete on public.companies for each row execute function public.audit_change();
create trigger updated before update on public.companies for each row execute function public.touch_updated();
alter table public.people enable row level security;
create policy read_member on public.people for select to authenticated using(public.crm_role() in ('admin','manager','viewer'));
create policy write_member on public.people for all to authenticated using(public.crm_role() in ('admin','manager')) with check(public.crm_role() in ('admin','manager'));
create trigger audit after insert or update or delete on public.people for each row execute function public.audit_change();
create trigger updated before update on public.people for each row execute function public.touch_updated();
alter table public.project_participants enable row level security;
create policy read_member on public.project_participants for select to authenticated using(public.crm_role() in ('admin','manager','viewer'));
create policy write_member on public.project_participants for all to authenticated using(public.crm_role() in ('admin','manager')) with check(public.crm_role() in ('admin','manager'));
create trigger audit after insert or update or delete on public.project_participants for each row execute function public.audit_change();
create trigger updated before update on public.project_participants for each row execute function public.touch_updated();
alter table public.project_participant_sections enable row level security;
create policy read_member on public.project_participant_sections for select to authenticated using(public.crm_role() in ('admin','manager','viewer'));
create policy write_member on public.project_participant_sections for all to authenticated using(public.crm_role() in ('admin','manager')) with check(public.crm_role() in ('admin','manager'));
create trigger audit after insert or update or delete on public.project_participant_sections for each row execute function public.audit_change();
create trigger updated before update on public.project_participant_sections for each row execute function public.touch_updated();
alter table public.project_sections enable row level security;
create policy read_member on public.project_sections for select to authenticated using(public.crm_role() in ('admin','manager','viewer'));
create policy write_member on public.project_sections for all to authenticated using(public.crm_role() in ('admin','manager')) with check(public.crm_role() in ('admin','manager'));
create trigger audit after insert or update or delete on public.project_sections for each row execute function public.audit_change();
create trigger updated before update on public.project_sections for each row execute function public.touch_updated();
alter table public.specifications enable row level security;
create policy read_member on public.specifications for select to authenticated using(public.crm_role() in ('admin','manager','viewer'));
create policy write_member on public.specifications for all to authenticated using(public.crm_role() in ('admin','manager')) with check(public.crm_role() in ('admin','manager'));
create trigger audit after insert or update or delete on public.specifications for each row execute function public.audit_change();
create trigger updated before update on public.specifications for each row execute function public.touch_updated();
alter table public.specification_items enable row level security;
create policy read_member on public.specification_items for select to authenticated using(public.crm_role() in ('admin','manager','viewer'));
create policy write_member on public.specification_items for all to authenticated using(public.crm_role() in ('admin','manager')) with check(public.crm_role() in ('admin','manager'));
create trigger audit after insert or update or delete on public.specification_items for each row execute function public.audit_change();
create trigger updated before update on public.specification_items for each row execute function public.touch_updated();
alter table public.products enable row level security;
create policy read_member on public.products for select to authenticated using(public.crm_role() in ('admin','manager','viewer'));
create policy write_member on public.products for all to authenticated using(public.crm_role() in ('admin','manager')) with check(public.crm_role() in ('admin','manager'));
create trigger audit after insert or update or delete on public.products for each row execute function public.audit_change();
create trigger updated before update on public.products for each row execute function public.touch_updated();
alter table public.product_matches enable row level security;
create policy read_member on public.product_matches for select to authenticated using(public.crm_role() in ('admin','manager','viewer'));
create policy write_member on public.product_matches for all to authenticated using(public.crm_role() in ('admin','manager')) with check(public.crm_role() in ('admin','manager'));
create trigger audit after insert or update or delete on public.product_matches for each row execute function public.audit_change();
create trigger updated before update on public.product_matches for each row execute function public.touch_updated();
alter table public.calculations enable row level security;
create policy read_member on public.calculations for select to authenticated using(public.crm_role() in ('admin','manager','viewer'));
create policy write_member on public.calculations for all to authenticated using(public.crm_role() in ('admin','manager')) with check(public.crm_role() in ('admin','manager'));
create trigger audit after insert or update or delete on public.calculations for each row execute function public.audit_change();
create trigger updated before update on public.calculations for each row execute function public.touch_updated();
alter table public.calculation_items enable row level security;
create policy read_member on public.calculation_items for select to authenticated using(public.crm_role() in ('admin','manager','viewer'));
create policy write_member on public.calculation_items for all to authenticated using(public.crm_role() in ('admin','manager')) with check(public.crm_role() in ('admin','manager'));
create trigger audit after insert or update or delete on public.calculation_items for each row execute function public.audit_change();
create trigger updated before update on public.calculation_items for each row execute function public.touch_updated();
alter table public.opportunities enable row level security;
create policy read_member on public.opportunities for select to authenticated using(public.crm_role() in ('admin','manager','viewer'));
create policy write_member on public.opportunities for all to authenticated using(public.crm_role() in ('admin','manager')) with check(public.crm_role() in ('admin','manager'));
create trigger audit after insert or update or delete on public.opportunities for each row execute function public.audit_change();
create trigger updated before update on public.opportunities for each row execute function public.touch_updated();
alter table public.activities enable row level security;
create policy read_member on public.activities for select to authenticated using(public.crm_role() in ('admin','manager','viewer'));
create policy write_member on public.activities for all to authenticated using(public.crm_role() in ('admin','manager')) with check(public.crm_role() in ('admin','manager'));
create trigger audit after insert or update or delete on public.activities for each row execute function public.audit_change();
create trigger updated before update on public.activities for each row execute function public.touch_updated();
alter table public.sources enable row level security;
create policy read_member on public.sources for select to authenticated using(public.crm_role() in ('admin','manager','viewer'));
create policy write_member on public.sources for all to authenticated using(public.crm_role() in ('admin','manager')) with check(public.crm_role() in ('admin','manager'));
create trigger audit after insert or update or delete on public.sources for each row execute function public.audit_change();
create trigger updated before update on public.sources for each row execute function public.touch_updated();
alter table public.profiles enable row level security;
create policy read_member on public.profiles for select to authenticated using(public.crm_role() in ('admin','manager','viewer'));
create policy write_member on public.profiles for all to authenticated using(public.crm_role() in ('admin')) with check(public.crm_role() in ('admin'));
create trigger audit after insert or update or delete on public.profiles for each row execute function public.audit_change();
create trigger updated before update on public.profiles for each row execute function public.touch_updated();
alter table public.history enable row level security;
create policy read_member on public.history for select to authenticated using(public.crm_role() in ('admin','manager','viewer'));
grant usage on schema public to authenticated;
grant select,insert,update,delete on all tables in schema public to authenticated;
revoke insert,update,delete on public.history from authenticated;
create index participant_project_idx on project_participants(project_id);
create index participant_company_idx on project_participants(company_id);
create index specs_project_idx on specifications(project_id);
create index history_project_idx on history(project_id,created_at desc);
create function public.import_legacy(payload jsonb) returns void language plpgsql security definer set search_path=public as $$
declare t text;keys text;begin
 foreach t in array array['projects','companies','people','project_participants','sources'] loop
   select string_agg(quote_ident(key),',') into keys from jsonb_object_keys(payload->t->0) as key;
   if keys is not null then execute format('insert into public.%I (%s) select %s from jsonb_populate_recordset(null::public.%I,$1) on conflict do nothing',t,keys,keys,t) using payload->t;end if;
 end loop;
end $$;
revoke all on function public.import_legacy(jsonb) from public,anon,authenticated;
grant execute on function public.import_legacy(jsonb) to service_role;
insert into storage.buckets(id,name,public,file_size_limit) values('specifications','specifications',false,20971520) on conflict(id) do nothing;
create policy spec_read on storage.objects for select to authenticated using(bucket_id='specifications' and public.crm_role() in ('admin','manager','viewer'));
create policy spec_write on storage.objects for insert to authenticated with check(bucket_id='specifications' and public.crm_role() in ('admin','manager') and (storage.foldername(name))[1] in (select id from public.projects));
create policy spec_delete on storage.objects for delete to authenticated using(bucket_id='specifications' and public.crm_role() in ('admin','manager'));
commit;
